// This file is auto-generated by scripts/codegen.mjs
// Do not edit directly - modify package.json and run the codegen script instead

export type MarimoCommand =
  | "marimo.clearRecentNotebooks"
  | "marimo.createSetupCell"
  | "marimo.exportStaticHTML"
  | "marimo.newMarimoNotebook"
  | "marimo.openAsMarimoNotebook"
  | "marimo.openTutorial"
  | "marimo.publishMarimoNotebook"
  | "marimo.publishMarimoNotebookGist"
  | "marimo.refreshPackages"
  | "marimo.reportIssue"
  | "marimo.restartKernel"
  | "marimo.restartLsp"
  | "marimo.runStale"
  | "marimo.showDiagnostics"
  | "marimo.showMarimoMenu"
  | "marimo.toggleOnCellChangeAutoRun"
  | "marimo.toggleOnCellChangeLazy";

export type MarimoView =
  | "marimo-explorer-datasources"
  | "marimo-explorer-packages"
  | "marimo-explorer-recents"
  | "marimo-explorer-variables";

export const NOTEBOOK_TYPE = "marimo-notebook";

export const SETUP_CELL_NAME = "setup";

export type MarimoContextKey =
  | "marimo.config.runtime.on_cell_change"
  | "marimo.isPythonFileMarimoNotebook"
  | "marimo.notebook.hasStaleCells";
