// This file is auto-generated by scripts/codegen.mjs
// Do not edit directly - modify package.json and run the codegen script instead

export type MarimoCommand =
  | "marimo.clearRecentNotebooks"
  | "marimo.createSetupCell"
  | "marimo.exportStaticHTML"
  | "marimo.newMarimoNotebook"
  | "marimo.openAsMarimoNotebook"
  | "marimo.openTutorial"
  | "marimo.publishMarimoNotebook"
  | "marimo.publishMarimoNotebookGist"
  | "marimo.refreshPackages"
  | "marimo.reportIssue"
  | "marimo.restartKernel"
  | "marimo.restartLsp"
  | "marimo.runStale"
  | "marimo.showDiagnostics"
  | "marimo.showMarimoMenu"
  | "marimo.toggleOnCellChangeAutoRun"
  | "marimo.toggleOnCellChangeLazy"
  | "marimo.updateActivePythonEnvironment";

export type MarimoView =
  | "marimo-explorer-datasources"
  | "marimo-explorer-packages"
  | "marimo-explorer-recents"
  | "marimo-explorer-variables";

export const NOTEBOOK_TYPE = "marimo-notebook" as const;

export const SETUP_CELL_NAME = "setup";

export const LanguageId = {
  /**
   * Language ID for Python cells in marimo notebooks.
   *
   * Using a custom language ID ("mo-python") prevents other
   * Python language servers from providing duplicate completions
   * and diagnostics.
   */
  Python: "mo-python",
  /** Language ID for SQL cells in marimo notebooks. */
  Sql: "sql",
  /** Language ID for Markdown cells in marimo notebooks. */
  Markdown: "markdown",
} as const;

export type MarimoContextKey =
  | "marimo.config.runtime.on_cell_change"
  | "marimo.isPythonFileMarimoNotebook"
  | "marimo.notebook.hasStaleCells";
