// This file is auto-generated by scripts/codegen.mjs
// Do not edit directly - modify package.json and run the codegen script instead

export type MarimoCommand =
  | "marimo.clearRecentNotebooks"
  | "marimo.newMarimoNotebook"
  | "marimo.publishMarimoNotebook"
  | "marimo.publishMarimoNotebookGist"
  | "marimo.refreshPackages"
  | "marimo.runStale"
  | "marimo.showMarimoMenu";

export type MarimoView =
  | "marimo-explorer-datasources"
  | "marimo-explorer-packages"
  | "marimo-explorer-recents"
  | "marimo-explorer-variables";

export const NOTEBOOK_TYPE = "marimo-notebook";

export type MarimoContextKey = "marimo.hasStaleCells";
