fail_fast: false

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
    hooks:
      - id: check-yaml
        exclude: ^extension/pnpm-lock\.yaml$
      - id: trailing-whitespace

  - repo: https://github.com/rhysd/actionlint
    rev: 914e7df21a07ef503a81201c76d2b11c789d3fca  # frozen: v1.7.12
    hooks:
      - id: actionlint
        args: [-ignore, SC]

  - repo: https://github.com/abravalheri/validate-pyproject
    rev: 4b2e70d08cb2ccd26d1fba73588de41c7a5d50b7  # frozen: v0.25
    hooks:
      - id: validate-pyproject

  - repo: https://github.com/crate-ci/typos
    rev: 37bb98842b0d8c4ffebdb75301a13db0267cef89  # frozen: v1.47.2
    hooks:
      - id: typos
        pass_filenames: false

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 22f0422809455ec89ffdcf5a00170ba816e42ddb  # frozen: v0.15.16
    hooks:
      # Run the linter
      - id: ruff
        args: [--fix]
      # Run the formatter
      - id: ruff-format
