// @ts-check
/// <reference lib="esnext" />
/**
 * @module codegen
 *
 * Generates TypeScript type definitions from package.json.
 * Do not edit the generated output file directly - modify package.json instead.
 *
 * Usage: node scripts/codegen.mjs
 */

import assert from "node:assert";
import * as NodeChildProcess from "node:child_process";
import * as NodeFs from "node:fs";
import * as NodeUrl from "node:url";

import * as semver from "@std/semver";
import { Schema } from "effect";

import pkg from "../package.json" with { type: "json" };

const Command = Schema.Struct({ command: Schema.String });
const View = Schema.Struct({ id: Schema.String });
const Notebook = Schema.Struct({ type: Schema.String });
const PackageJson = Schema.Struct({
  contributes: Schema.Struct({
    commands: Schema.Array(Command),
    views: Schema.Record({ key: Schema.String, value: Schema.Array(View) }),
    notebooks: Schema.Tuple(Notebook),
  }),
});

const { contributes } = Schema.decodeUnknownSync(PackageJson)(pkg);
const commands = contributes.commands.map((c) => c.command);
const notebookType = contributes.notebooks[0].type;

const pyproject = NodeFs.readFileSync(
  NodeUrl.fileURLToPath(new URL("../../pyproject.toml", import.meta.url)),
  "utf-8",
);
const minimumMarimoVersion = semver.parse(
  pyproject.match(/marimo>=([\d.]+)/)?.[1] ?? "",
);

const views = Object.keys(contributes.views);
assert(
  views.length === 1,
  `Expected view contribution, found multiple: ${JSON.stringify(views)}`,
);
const viewIds = contributes.views[views[0]].map((v) => v.id);

const contextKeys = [
  "marimo.notebook.hasStaleCells",
  "marimo.notebook.hasKernel",
  "marimo.config.runtime.on_cell_change",
  "marimo.config.runtime.auto_reload",
  "marimo.isPythonFileMarimoNotebook",
];

/** @type {(arr: Array<string>) => string} */
const union = (arr) =>
  arr
    .toSorted()
    .map((name) => JSON.stringify(name))
    .join(" | ");

const code = NodeChildProcess.execFileSync(
  NodeUrl.fileURLToPath(new URL("../node_modules/.bin/vp", import.meta.url)),
  ["fmt", "--stdin-filepath", "constants.ts"],
  {
    input: `\
// This file is auto-generated by scripts/codegen.mjs
// Do not edit directly - modify package.json and run the codegen script instead

export type MarimoCommand = ${union(commands)};

export type MarimoView = ${union(viewIds)};

export const NOTEBOOK_TYPE = "${notebookType}";

export const SETUP_CELL_NAME = "setup";

export const SCRATCH_CELL_ID = "__scratch__";

export const LanguageId = {
  /**
   * Language ID for Python cells in marimo notebooks.
   *
   * Using a custom language ID ("mo-python") prevents other
   * Python language servers from providing duplicate completions
   * and diagnostics.
   */
  Python: "mo-python",
  /** Language ID for SQL cells in marimo notebooks. */
  Sql: "sql",
  /** Language ID for Markdown cells in marimo notebooks. */
  Markdown: "markdown",
} as const;

export const MINIMUM_MARIMO_VERSION = {
  major: ${minimumMarimoVersion.major},
  minor: ${minimumMarimoVersion.minor},
  patch: ${minimumMarimoVersion.patch},
} as const;

export type MarimoContextKey = ${union(contextKeys)};
`,
    encoding: "utf-8",
  },
);

const outputPath = NodeUrl.fileURLToPath(
  new URL("../src/constants.ts", import.meta.url),
);
NodeFs.writeFileSync(outputPath, code);
console.log(`✓ Wrote to ${outputPath}`);
